name: apodock
channels:
  - defaults
  - bioconda
  - conda-forge
  - esri
  - nvidia
  - pytorch
  - pyg
dependencies:
  - biopython
  - dm-tree
  - einops
  - ml-collections
  - networkx
  - numpy=1.24
  - pandas
  - pip
  - prody
  - pymol-open-source
  - python=3.8
  - pytorch
  - pytorch-mutex
  - rdkit
  - scikit-learn
  - scikit-learn-extra
  - scipy
  - torchaudio
  - torch-cluster
  - torch-geometric
  - torch-scatter
  - torchvision
